# CMake generated Testfile for 
# Source directory: G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master
# Build directory: G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-no-opt")
  set_tests_properties(spirv-cross-test-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-no-opt")
  set_tests_properties(spirv-cross-test-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-no-opt")
  set_tests_properties(spirv-cross-test-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-no-opt")
  set_tests_properties(spirv-cross-test-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-no-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-metal "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-metal "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-metal "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-metal "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-metal NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-metal-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl-no-opt")
  set_tests_properties(spirv-cross-test-metal-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-metal-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl-no-opt")
  set_tests_properties(spirv-cross-test-metal-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-metal-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl-no-opt")
  set_tests_properties(spirv-cross-test-metal-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-metal-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl-no-opt")
  set_tests_properties(spirv-cross-test-metal-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-metal-no-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-hlsl "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-hlsl "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-hlsl "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-hlsl "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-hlsl NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-hlsl-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl-no-opt")
  set_tests_properties(spirv-cross-test-hlsl-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-hlsl-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl-no-opt")
  set_tests_properties(spirv-cross-test-hlsl-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-hlsl-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl-no-opt")
  set_tests_properties(spirv-cross-test-hlsl-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-hlsl-no-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl-no-opt")
  set_tests_properties(spirv-cross-test-hlsl-no-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-hlsl-no-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders")
  set_tests_properties(spirv-cross-test-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-metal-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-metal-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-metal-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-metal-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--metal" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-msl")
  set_tests_properties(spirv-cross-test-metal-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-metal-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-hlsl-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-hlsl-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-hlsl-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-hlsl-opt "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--hlsl" "--opt" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-hlsl")
  set_tests_properties(spirv-cross-test-hlsl-opt PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-hlsl-opt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(spirv-cross-test-reflection "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--reflect" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-reflection")
  set_tests_properties(spirv-cross-test-reflection PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Debug")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(spirv-cross-test-reflection "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--reflect" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-reflection")
  set_tests_properties(spirv-cross-test-reflection PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/Release")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(spirv-cross-test-reflection "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--reflect" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-reflection")
  set_tests_properties(spirv-cross-test-reflection PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/MinSizeRel")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(spirv-cross-test-reflection "C:/Users/james/AppData/Local/Programs/Python/Python37-32/python.exe" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/test_shaders.py" "--reflect" "--parallel" "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/shaders-reflection")
  set_tests_properties(spirv-cross-test-reflection PROPERTIES  WORKING_DIRECTORY "G:/proj/Engines/Night Heron/Night Heron Engine/Dependencies/SPIRV-Cross-master/cmakeBuild/RelWithDebInfo")
else()
  add_test(spirv-cross-test-reflection NOT_AVAILABLE)
endif()
